#!/bin/bash

echo "Updating git"
#sudo rm /var/lib/apt/lists/lock
#sudo rm /var/cache/apt/archives/lock

sudo apt-get update > /dev/null 2>&1


echo "Installing git"
sudo apt-get install git -y --force-yes > /dev/null 2>&1
git config --global user.email "alecjohanson@gmail.com" > /dev/null 2>&1
git config --global user.name "Alec Johanson" > /dev/null 2>&1
git config --global push.default simple > /dev/null 2>&1

echo "Installing Curl"
sudo apt-get install curl -y --force-yes > /dev/null 2>&1

echo "Getting zsh"
sudo apt-get install zsh -y --force-yes > /dev/null 2>&1

echo "Now for oh-my-zsh"
curl -L http://install.ohmyz.sh | sh > /dev/null 2>&1

echo "Let's get you tmux"
sudo apt-get install tmux -y --force-yes > /dev/null 2>&1

echo "Oh, Vim, Can't forget vim"
sudo apt-get install vim -y --force-yes > /dev/null 2>&1

git clone git@github.com:alecjohanson/dotfiles.git

#gotta delete this stuff
#TODO MAKE this to move so we can put them back later?
sudo rm -rf ~/.tmux > /dev/null 2>&1
sudo rm -rf ~/.zsh-custom > /dev/null 2>&1
sudo rm -rf ~/.ctags > /dev/null 2>&1
sudo rm -rf ~/.gitignore > /dev/null 2>&1
sudo rm -rf ~/.gitmodules > /dev/null 2>&1
sudo rm -rf ~/.vimrc > /dev/null 2>&1
sudo rm -rf ~/.viminfo > /dev/null 2>&1
sudo rm -rf ~/.vim > /dev/null 2>&1
sudo rm -rf ~/.oh-my-zsh > /dev/null 2>&1
sudo rm -rf ~/.tmux.conf > /dev/null 2>&1
sudo rm -rf ~/.zshrc > /dev/null 2>&1
sudo rm -rf ~/.gitconfig > /dev/null 2>&1
sudo rm -rf ~/.zsh_prompt > /dev/null 2>&1
sudo rm -rf ~/.zsh-syntax-highlighting.zsh > /dev/null 2>&1
sudo rm -rf ~/highlighters > /dev/null 2>&1

echo "now we'll do some sym links"
ln -s ~/dotfiles/tmux/.tmux ~/.tmux
ln -s ~/dotfiles/tmux/tmux.conf ~/.tmux.conf
ln -s ~/dotfiles/zsh/zshrc ~/.zshrc
ln -s ~/dotfiles/vimrc/ ~/.vimrc


